/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Gozie
 */
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.KeyEvent;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import javax.swing.*;
import java.sql.*;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

public class mainHome extends javax.swing.JFrame {

    /**
     * Creates new form mainHome
     */
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    Statement st = null;
    DefaultTableModel lmf = new DefaultTableModel();
   
    public mainHome() {
        initComponents();
      conn = connectDB.connDB();
        getFaculty(faculty);
        getFaculty(faculty1);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dpt_board = new javax.swing.JLabel();
        faculty_board = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        name = new javax.swing.JLabel();
        level_board = new javax.swing.JLabel();
        level_board1 = new javax.swing.JLabel();
        levelGP = new javax.swing.JLabel();
        regn = new javax.swing.JLabel();
        level_board2 = new javax.swing.JLabel();
        finalUnit = new javax.swing.JLabel();
        level_board3 = new javax.swing.JLabel();
        finalGrade = new javax.swing.JLabel();
        gradeValue = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        level200 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        t2200 = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        t1200 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        l1200 = new javax.swing.JLabel();
        l2200 = new javax.swing.JLabel();
        level100 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        t2100 = new javax.swing.JTable();
        jScrollPane8 = new javax.swing.JScrollPane();
        t1100 = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        l1100 = new javax.swing.JLabel();
        l2100 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        level300 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        t2300 = new javax.swing.JTable();
        jScrollPane10 = new javax.swing.JScrollPane();
        t1300 = new javax.swing.JTable();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        l1300 = new javax.swing.JLabel();
        l2300 = new javax.swing.JLabel();
        level500 = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        t2500 = new javax.swing.JTable();
        jScrollPane12 = new javax.swing.JScrollPane();
        t1500 = new javax.swing.JTable();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        l1500 = new javax.swing.JLabel();
        l2500 = new javax.swing.JLabel();
        level400 = new javax.swing.JPanel();
        jScrollPane13 = new javax.swing.JScrollPane();
        t2400 = new javax.swing.JTable();
        jScrollPane14 = new javax.swing.JScrollPane();
        t1400 = new javax.swing.JTable();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        l1400 = new javax.swing.JLabel();
        l2400 = new javax.swing.JLabel();
        printBtn = new javax.swing.JButton();
        jDialog2 = new javax.swing.JDialog();
        jPanel10 = new javax.swing.JPanel();
        score = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        namedetail = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        faculty = new javax.swing.JComboBox<>();
        department = new javax.swing.JComboBox<>();
        level = new javax.swing.JComboBox<>();
        semester = new javax.swing.JComboBox<>();
        courses = new javax.swing.JComboBox<>();
        search_btn = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        faculty1 = new javax.swing.JComboBox<>();
        department1 = new javax.swing.JComboBox<>();
        level1 = new javax.swing.JComboBox<>();
        search_btn1 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        cgp_btn = new javax.swing.JButton();
        grade_btn = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jDialog1.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialog1.setBackground(new java.awt.Color(167, 207, 207));
        jDialog1.setMinimumSize(new java.awt.Dimension(1080, 645));
        jDialog1.setModalityType(java.awt.Dialog.ModalityType.DOCUMENT_MODAL);
        jDialog1.setResizable(false);
        jDialog1.setSize(new java.awt.Dimension(1080, 645));

        jPanel6.setBackground(new java.awt.Color(167, 207, 207));
        jPanel6.setMaximumSize(new java.awt.Dimension(1080, 1780));
        jPanel6.setMinimumSize(new java.awt.Dimension(1080, 700));
        jPanel6.setPreferredSize(new java.awt.Dimension(1080, 1780));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 11, -1, 107));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(245, 80, 75));
        jLabel5.setText("ENUGU STATE UNIVERSITY OF SCIENCE AND TECHNOLOGY");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 673, 42));

        dpt_board.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        dpt_board.setForeground(new java.awt.Color(245, 80, 75));
        jPanel6.add(dpt_board, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 600, 42));

        faculty_board.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        faculty_board.setForeground(new java.awt.Color(245, 80, 75));
        jPanel6.add(faculty_board, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 530, 42));
        jPanel6.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 1080, 10));
        jPanel6.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 470, 30));

        level_board.setText("CGPA :");
        jPanel6.add(level_board, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 290, 50, 30));

        level_board1.setText("LEVEL:");
        jPanel6.add(level_board1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 180, 50, 30));
        jPanel6.add(levelGP, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 180, 140, 30));
        jPanel6.add(regn, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 330, 320, 30));

        level_board2.setText("TOTAL CREDIT UNIT:");
        jPanel6.add(level_board2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 210, 120, 30));
        jPanel6.add(finalUnit, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 210, 100, 30));

        level_board3.setText("TOTAL GRADE UNIT:");
        jPanel6.add(level_board3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 250, 120, 30));
        jPanel6.add(finalGrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 250, 100, 30));
        jPanel6.add(gradeValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 290, 210, 30));
        jPanel6.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 1080, 10));

        level200.setBackground(new java.awt.Color(167, 207, 207));
        level200.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        t2200.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane5.setViewportView(t2200);

        level200.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 40, 510, 190));

        t1200.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane6.setViewportView(t1200);

        level200.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 490, 190));

        jLabel6.setText("200 Level Second Semester");
        level200.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 510, 30));

        jLabel14.setText("200 Level First Semester");
        level200.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 490, 30));
        level200.add(l1200, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 490, 30));
        level200.add(l2200, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, 510, 30));

        jPanel6.add(level200, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 650, 1050, 260));

        level100.setBackground(new java.awt.Color(167, 207, 207));
        level100.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        t2100.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane7.setViewportView(t2100);

        level100.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 40, 510, 190));

        t1100.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane8.setViewportView(t1100);

        level100.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 490, 190));

        jLabel23.setText("100 Level Second Semester");
        level100.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 510, 30));
        level100.add(l1100, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 490, 30));
        level100.add(l2100, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, 510, 30));

        jLabel24.setText("100 Level First Semester");
        level100.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 490, 30));

        jPanel6.add(level100, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 1050, 260));

        level300.setBackground(new java.awt.Color(167, 207, 207));
        level300.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        t2300.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane9.setViewportView(t2300);

        level300.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 510, 200));

        t1300.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane10.setViewportView(t1300);

        level300.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 490, 200));

        jLabel27.setText("300 Level Second Semester");
        level300.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 510, 30));

        jLabel28.setText("300 Level First Semester");
        level300.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 490, 30));
        level300.add(l1300, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 490, 30));
        level300.add(l2300, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, 510, 30));

        jPanel6.add(level300, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 920, 1050, 260));

        level500.setBackground(new java.awt.Color(167, 207, 207));
        level500.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        t2500.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane11.setViewportView(t2500);

        level500.add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 510, 200));

        t1500.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane12.setViewportView(t1500);

        level500.add(jScrollPane12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 490, 200));

        jLabel31.setText("500 Level Second Semester");
        level500.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 510, 30));

        jLabel32.setText("500 Level First Semester");
        level500.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 490, 30));
        level500.add(l1500, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 490, 30));
        level500.add(l2500, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, 510, 30));

        jPanel6.add(level500, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 1460, 1050, 260));

        level400.setBackground(new java.awt.Color(167, 207, 207));
        level400.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        t2400.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane13.setViewportView(t2400);

        level400.add(jScrollPane13, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 510, 200));

        t1400.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane14.setViewportView(t1400);

        level400.add(jScrollPane14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 490, 200));

        jLabel35.setText("400 Level Second Semester");
        level400.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 510, 30));

        jLabel36.setText("400 Level First Semester");
        level400.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 490, 30));
        level400.add(l1400, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 490, 30));
        level400.add(l2400, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, 510, 30));

        jPanel6.add(level400, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 1190, 1050, 260));

        printBtn.setBackground(new java.awt.Color(0, 255, 255));
        printBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        printBtn.setForeground(new java.awt.Color(255, 255, 255));
        printBtn.setText("Print");
        printBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printBtnActionPerformed(evt);
            }
        });
        jPanel6.add(printBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 120, -1));

        jScrollPane4.setViewportView(jPanel6);

        jDialog1.getContentPane().add(jScrollPane4, java.awt.BorderLayout.LINE_END);

        jDialog2.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialog2.setMinimumSize(new java.awt.Dimension(460, 250));
        jDialog2.setResizable(false);
        jDialog2.setSize(new java.awt.Dimension(460, 250));
        jDialog2.setType(java.awt.Window.Type.POPUP);

        jPanel10.setBackground(new java.awt.Color(167, 207, 207));
        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel10.setMaximumSize(new java.awt.Dimension(460, 250));
        jPanel10.setMinimumSize(new java.awt.Dimension(460, 250));
        jPanel10.setPreferredSize(new java.awt.Dimension(460, 250));

        score.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scoreActionPerformed(evt);
            }
        });
        score.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                scoreKeyTyped(evt);
            }
        });

        add.setBackground(new java.awt.Color(0, 255, 255));
        add.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("ENTER STUDENT SCORE");

        namedetail.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        namedetail.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(namedetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(score, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 99, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namedetail, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                .addGap(11, 11, 11)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(score, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        jDialog2.getContentPane().add(jPanel10, java.awt.BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CGPA CALCULATOR ESUT");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(167, 207, 207));

        jScrollPane1.setBackground(new java.awt.Color(167, 207, 207));

        jPanel2.setBackground(new java.awt.Color(167, 207, 207));
        jPanel2.setMaximumSize(new java.awt.Dimension(1200, 800));
        jPanel2.setMinimumSize(new java.awt.Dimension(1200, 800));
        jPanel2.setPreferredSize(new java.awt.Dimension(1200, 800));
        jPanel2.setLayout(new java.awt.CardLayout());

        jPanel15.setBackground(new java.awt.Color(167, 207, 207));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel15, "card3");

        jPanel11.setBackground(new java.awt.Color(167, 207, 207));

        jPanel12.setBackground(new java.awt.Color(167, 207, 207));
        jPanel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setText("FACULTY");
        jPanel12.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 26, 66, -1));

        jLabel9.setText("DEPARTMENT");
        jPanel12.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 64, -1, -1));

        jLabel10.setText("LEVEL");
        jPanel12.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 66, 20));

        jLabel11.setText("SEMESTER");
        jPanel12.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 66, -1));

        jLabel12.setText("COURSE");
        jPanel12.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        faculty.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                facultyPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jPanel12.add(faculty, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 224, 30));

        department.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                departmentPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jPanel12.add(department, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 224, 30));

        level.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "100", "200", "300", "400", "500" }));
        level.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                levelPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jPanel12.add(level, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 224, 30));

        semester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "1", "2" }));
        semester.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                semesterPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jPanel12.add(semester, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 224, 30));

        jPanel12.add(courses, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 240, 40));

        search_btn.setBackground(new java.awt.Color(0, 255, 255));
        search_btn.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        search_btn.setForeground(new java.awt.Color(255, 255, 255));
        search_btn.setText("Search");
        search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_btnActionPerformed(evt);
            }
        });
        jPanel12.add(search_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 110, 30));

        jPanel13.setBackground(new java.awt.Color(167, 207, 207));
        jPanel13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 792, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel11, "card2");

        jPanel5.setBackground(new java.awt.Color(167, 207, 207));

        jPanel7.setBackground(new java.awt.Color(167, 207, 207));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("FACULTY");
        jPanel7.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 26, 66, -1));

        jLabel2.setText("DEPARTMENT");
        jPanel7.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 64, -1, -1));

        jLabel3.setText("LEVEL");
        jPanel7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 66, 20));

        faculty1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                faculty1PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jPanel7.add(faculty1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 224, 30));

        jPanel7.add(department1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 224, 30));

        level1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "100", "200", "300", "400", "500" }));
        jPanel7.add(level1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 224, 30));

        search_btn1.setBackground(new java.awt.Color(0, 255, 255));
        search_btn1.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        search_btn1.setForeground(new java.awt.Color(255, 255, 255));
        search_btn1.setText("Search");
        search_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_btn1ActionPerformed(evt);
            }
        });
        jPanel7.add(search_btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 110, 30));

        jPanel8.setBackground(new java.awt.Color(167, 207, 207));
        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 792, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel5, "card2");

        jScrollPane1.setViewportView(jPanel2);

        jPanel3.setBackground(new java.awt.Color(167, 207, 207));
        jPanel3.setLayout(new java.awt.CardLayout());

        jPanel4.setBackground(new java.awt.Color(167, 207, 207));

        cgp_btn.setBackground(new java.awt.Color(0, 255, 255));
        cgp_btn.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        cgp_btn.setForeground(new java.awt.Color(255, 255, 255));
        cgp_btn.setText("CALCULATE CGP");
        cgp_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cgp_btnActionPerformed(evt);
            }
        });

        grade_btn.setBackground(new java.awt.Color(0, 255, 255));
        grade_btn.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        grade_btn.setForeground(new java.awt.Color(255, 255, 255));
        grade_btn.setText("ADD GRADE");
        grade_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grade_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(grade_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(cgp_btn)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(grade_btn)
                .addGap(7, 7, 7)
                .addComponent(cgp_btn)
                .addGap(391, 391, 391))
        );

        jPanel3.add(jPanel4, "card2");

        jLabel15.setFont(new java.awt.Font("Arial Black", 1, 30)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("CGPA CALCULATOR ESUT");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 857, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(241, 241, 241))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void grade_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grade_btnActionPerformed
        jPanel2.removeAll();
        jPanel2.add(jPanel11);
        jPanel2.validate();
        jPanel2.repaint();

    }//GEN-LAST:event_grade_btnActionPerformed

    private void departmentPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_departmentPopupMenuWillBecomeInvisible
    courses.removeAllItems();
    }//GEN-LAST:event_departmentPopupMenuWillBecomeInvisible

    private void facultyPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_facultyPopupMenuWillBecomeInvisible
        fillDepartment(department,faculty);
        courses.removeAllItems();
    }//GEN-LAST:event_facultyPopupMenuWillBecomeInvisible

    private void semesterPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_semesterPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        fillcourse();
    }//GEN-LAST:event_semesterPopupMenuWillBecomeInvisible

    private void search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_btnActionPerformed
        // TODO add your handling code here:
        fillTable();
    }//GEN-LAST:event_search_btnActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:]
//         jTable2.setModel(new DefaultTableModel() {
//
//    @Override
//    public boolean isCellEditable(int row, int column) {
//       return false;
//    }
//});
           boolean a = jTable2.isEditing();
           if(a == false){
               
       int getrow = jTable2.getSelectedRow();
       String surname = (String)jTable2.getModel().getValueAt(getrow, 0);
       String middlename = (String)jTable2.getModel().getValueAt(getrow, 1);
       String lastname = (String)jTable2.getModel().getValueAt(getrow, 2);
       namedetail.setText(surname +" "+middlename+" "+lastname);
               jDialog2.setLocationRelativeTo(null);
               jDialog2.setVisible(true);
           }
    }//GEN-LAST:event_jTable2MouseClicked

    private void scoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scoreActionPerformed

    private void levelPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_levelPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        courses.removeAllItems();
    }//GEN-LAST:event_levelPopupMenuWillBecomeInvisible

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        enter_score();
    }//GEN-LAST:event_addActionPerformed

    private void scoreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_scoreKeyTyped
        // TODO add your handling code here:
         char c = evt.getKeyChar();
        if(!(Character.isDigit(c))|| (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE)){
            getToolkit().beep();
            evt.consume();
        }
       
    }//GEN-LAST:event_scoreKeyTyped

    private void cgp_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cgp_btnActionPerformed
        // TODO add your handling code here:
          jPanel2.removeAll();
        jPanel2.add(jPanel5);
        jPanel2.validate();
        jPanel2.repaint();
    }//GEN-LAST:event_cgp_btnActionPerformed

    private void faculty1PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_faculty1PopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        fillDepartment(department1,faculty1);
    }//GEN-LAST:event_faculty1PopupMenuWillBecomeInvisible

    private void search_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_btn1ActionPerformed
        // TODO add your handling code here:
       display_gp();
    }//GEN-LAST:event_search_btn1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
          boolean a = jTable1.isEditing();
           if(a == false){
               
       filter_level();
       
               jDialog1.setLocationRelativeTo(null);
               jDialog1.setVisible(true);
           }
    }//GEN-LAST:event_jTable1MouseClicked

    private void printBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printBtnActionPerformed
        // TODO add your handling code here:'printComponenet
        printComponenet(jPanel6);
    }//GEN-LAST:event_printBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton cgp_btn;
    private javax.swing.JComboBox<String> courses;
    private javax.swing.JComboBox<String> department;
    private javax.swing.JComboBox<String> department1;
    private javax.swing.JLabel dpt_board;
    private javax.swing.JComboBox<String> faculty;
    private javax.swing.JComboBox<String> faculty1;
    private javax.swing.JLabel faculty_board;
    private javax.swing.JLabel finalGrade;
    private javax.swing.JLabel finalUnit;
    private javax.swing.JLabel gradeValue;
    private javax.swing.JButton grade_btn;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel l1100;
    private javax.swing.JLabel l1200;
    private javax.swing.JLabel l1300;
    private javax.swing.JLabel l1400;
    private javax.swing.JLabel l1500;
    private javax.swing.JLabel l2100;
    private javax.swing.JLabel l2200;
    private javax.swing.JLabel l2300;
    private javax.swing.JLabel l2400;
    private javax.swing.JLabel l2500;
    private javax.swing.JComboBox<String> level;
    private javax.swing.JComboBox<String> level1;
    private javax.swing.JPanel level100;
    private javax.swing.JPanel level200;
    private javax.swing.JPanel level300;
    private javax.swing.JPanel level400;
    private javax.swing.JPanel level500;
    private javax.swing.JLabel levelGP;
    private javax.swing.JLabel level_board;
    private javax.swing.JLabel level_board1;
    private javax.swing.JLabel level_board2;
    private javax.swing.JLabel level_board3;
    private javax.swing.JLabel name;
    private javax.swing.JLabel namedetail;
    private javax.swing.JButton printBtn;
    private javax.swing.JLabel regn;
    private javax.swing.JTextField score;
    private javax.swing.JButton search_btn;
    private javax.swing.JButton search_btn1;
    private javax.swing.JComboBox<String> semester;
    private javax.swing.JTable t1100;
    private javax.swing.JTable t1200;
    private javax.swing.JTable t1300;
    private javax.swing.JTable t1400;
    private javax.swing.JTable t1500;
    private javax.swing.JTable t2100;
    private javax.swing.JTable t2200;
    private javax.swing.JTable t2300;
    private javax.swing.JTable t2400;
    private javax.swing.JTable t2500;
    // End of variables declaration//GEN-END:variables

public void getFaculty(JComboBox fac ){
     try{
         String sql = "select * from faculty";
          pst=conn.prepareStatement(sql);
          rs=pst.executeQuery();
     
         while(rs.next()){
         String facultyName = rs.getString("FACULTY");
       fac.addItem(facultyName); 
         
         }
          
     }catch(SQLException e){
     JOptionPane.showMessageDialog(null, e);
     }
     finally {
try{
  rs.close();
      pst.close();
    // conn.close();
  }
  catch(SQLException e) {
                   }
      }
}

  public void fillDepartment(JComboBox dept, JComboBox fac){
           
           dept.removeAllItems();
           connectDB dm = new connectDB();
           ArrayList<deptClass> list = dm.getData((int)fac.getSelectedIndex());
            
                    for(int i = 0; i < list.size(); i++){
                      dept.addItem(list.get(i).getFaculty_name());                 
            }
           }
  public static String  grade_level( double cgpa){
 String gradeLevel;
 if(cgpa >= 4.50){
  gradeLevel = "FIRST CLASS";
 }else if (cgpa >= 3.50) {
  gradeLevel = "SECOND CLASS UPPER";
 }else if (cgpa >= 2.50) {
  gradeLevel = "SECOND CLASS LOWER";
 }else if (cgpa >= 1.50) {
  gradeLevel = "THIRD CLASS";
 }else{
  gradeLevel = "PASS";
 }
 return gradeLevel;
         }
  
  public static char   calculate_grade(int grade){
      char gradeValue ;
      if(grade >= 70){
        gradeValue = 'A';
      }else if(grade >= 60){
        gradeValue = 'B';
      }else if(grade >= 50){
        gradeValue = 'C';
      }else if(grade >= 45){
        gradeValue = 'D';
      }else {
        gradeValue = 'F';
      }
      return gradeValue;
     }
  
  public static int  getgrade_point( char grade){
      int gradeValue;
      switch(grade){
        case 'A':
        gradeValue = 5;
        break;
        case 'B':
        gradeValue = 4;
        break;
        case 'C':
        gradeValue = 3;
        break;
        case 'D':
        gradeValue = 2;
        break;
        default:
        gradeValue = 0;
        break;
      }
      return gradeValue;
     }
  
  public void fillTable(){
      
      clearTable (); 
     
            
          Object[] col = new Object[10];
          Object[] row = new Object[10];
            col[0] = "Surname";
            col[1] = "Middlename";
            col[2] = "Lastname";
            col[3] = "Reg. Number";
            col[4] =  "Course Tittle";
            col[5] = "ourse Code";
            col[6] = "Credit Load";
            col[7] = "Score";
            col[8] = "Grade";
            col[9] =  "Grade Point";
            
            lmf.setColumnIdentifiers(col);
            
         
            
            for(int e= 0; e< getTable().size();e++){
                row[0] = getTable().get(e).getSurname();
                row[1] = getTable().get(e).getFirstname();
                row[2] = getTable().get(e).getLastname();
                row[3] = getTable().get(e).getRegNumber();  
                row[4] = getTable().get(e).getTittle();
                row[5] = getTable().get(e).getCode();
                row[6] = getTable().get(e).getCredit();
                row[7] = getTable().get(e).getScore();
                row[8] = getTable().get(e).getGrade();  
                row[9] = getTable().get(e).getGrade_unit();;  
                lmf.addRow(row);   
            }  
          
            jTable2.setModel(lmf);
           
      }
     public void clearTable (){
           jTable2.getModel();
           jTable1.getModel();
           lmf.setRowCount(0);
           
      }

  
  public void fillcourse(){
      courses.removeAllItems();
       String dept = (String)department.getSelectedItem();
            String lvl = (String)level.getSelectedItem();
      String sem = (String)semester.getSelectedItem();
      try{
          String qle = "select * from engineering where department = '"+dept+"' and level = '"+lvl+"' and semester = '"+sem+"'";
          pst = conn.prepareStatement(qle);
          rs = pst.executeQuery();
          while(rs.next()){
              courses.addItem(rs.getString("courseTittle"));
          }
      }catch(Exception e){
       JOptionPane.showConfirmDialog(null, e);   
      }
  }
   class courseData{
        private String surname;
         private String firstname;
        private String lastname;
        private String regNumber;
       private String tittle;
         private String code;
        private int credit;
        private int score;  
         private String grade; 
        private int grade_unit;

    
    public courseData (String Surname,String Firstname,String Lastname,String RegNumber,  String Tittle,
          String Code,
         int Credit,
         int Score,  
          String Grade,
         int Grade_unit){
     
        this.surname = Surname;
        this.firstname = Firstname;
        this.lastname = Lastname;
        this.regNumber = RegNumber;
       this.tittle = Tittle;
        this.code = Code;        
        this.credit = Credit;
        this.score = Score;
        this.grade = Grade;  
        this.grade_unit = Grade_unit;

    }    

        public String getSurname() {
            return surname;
        }

        public void setSurname(String surname) {
            this.surname = surname;
        }

        public String getFirstname() {
            return firstname;
        }

        public void setFirstname(String firstname) {
            this.firstname = firstname;
        }

        public String getLastname() {
            return lastname;
        }

        public void setLastname(String lastname) {
            this.lastname = lastname;
        }

        public String getRegNumber() {
            return regNumber;
        }

        public void setRegNumber(String regNumber) {
            this.regNumber = regNumber;
        }

        public String getTittle() {
            return tittle;
        }

        public void setTittle(String tittle) {
            this.tittle = tittle;
        }

        public String getCode() {
            return code;
        }

        public void setCode(String code) {
            this.code = code;
        }

        public int getCredit() {
            return credit;
        }

        public void setCredit(int credit) {
            this.credit = credit;
        }

        public int getScore() {
            return score;
        }

        public void setScore(int score) {
            this.score = score;
        }

        public String getGrade() {
            return grade;
        }

        public void setGrade(String grade) {
            this.grade = grade;
        }

        public int getGrade_unit() {
            return grade_unit;
        }

        public void setGrade_unit(int grade_unit) {
            this.grade_unit = grade_unit;
        }
    
 }
   public ArrayList<courseData>getTable(){
    String dept = (String)department.getSelectedItem();
            String lvl = (String)level.getSelectedItem();
      String sem = (String)semester.getSelectedItem();
      String cours = (String)courses.getSelectedItem();
     
        ArrayList<courseData> courseDetail = new ArrayList<courseData>();
      
        courseData c;
        try { 
            String squery = "select student.surname, student.middlename, student.lastname,"
                  + "student.regnumber, course.courseTittle, course.courseCode,course.creditLoad , course.score,course.grade,"
                    + " course.grade_unit  from student,course where student.regnumber = course.regno "
                  + "and course.level = '"+lvl+"' and course.courseTittle = '"+cours+"' and course.semester = '"+sem+"' ";
              pst=conn.prepareStatement(squery);
          rs=pst.executeQuery();
        while(rs.next()){
                    c = new courseData(
                             rs.getString("surname"),
                            rs.getString("middlename"),
                            rs.getString("lastname"),
                           rs.getString("regNumber"),
                             rs.getString("courseTittle"),
                            rs.getString("courseCode"),
                            rs.getInt("creditLoad"),
                           rs.getInt("score"),
                            rs.getString("grade"),
                           rs.getInt("grade_unit")
                          );
                    
                    courseDetail.add(c);
                }
               
    } catch (SQLException ex) {
        Logger.getLogger(mainHome.class.getName()).log(Level.SEVERE, null, ex);
    }
         finally {
try{
  rs.close();
      pst.close();
      //st.close();
    // conn.close();
  }
  catch(SQLException e) {
                   }
      }
         return courseDetail;        
    }
   
   public void enter_score(){
       if(score.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "A value is required");
           jDialog2.dispose();
       }else{
       int scorevalue = Integer.parseInt(score.getText());
       String lev = level.getSelectedItem().toString();
       int getrow = jTable2.getSelectedRow();
       int getcredit = (int)jTable2.getModel().getValueAt(getrow, 6);
       char gradevalue = calculate_grade(scorevalue);
       int gradepoint = getgrade_point(gradevalue) * getcredit;
       jTable2.getModel().setValueAt(scorevalue, getrow, 7);
       jTable2.getModel().setValueAt(gradevalue, getrow, 8);
       jTable2.getModel().setValueAt(gradepoint, getrow, 9);
       String regno = (String)jTable2.getModel().getValueAt(getrow, 3);
       String tittle = (String)jTable2.getModel().getValueAt(getrow, 4);
       int getscore = (int)jTable2.getModel().getValueAt(getrow, 7);
       char getgrade = (char)jTable2.getModel().getValueAt(getrow, 8);
       int getpoint = (int)jTable2.getModel().getValueAt(getrow, 9);
       try{
           String sql = "update course set score = '"+getscore+"',grade = '"+getgrade+"',grade_unit = '"+getpoint+"' where regno = '"+regno+"'"
                   + " and courseTittle = '"+tittle+"' and level = '"+lev+"'";
           pst = conn.prepareStatement(sql);
           pst.executeUpdate();
       }catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
       }
       
       score.setText(null);
       jDialog2.dispose();
   }
   }
   public void showdata(){
        
           
   }
   
   public void display_gp(){
//      int rowcount = jTable1.getModel().getRowCount();
      
       String fac = (String)faculty1.getSelectedItem();
       String dept = (String)department1.getSelectedItem();
       String lev = (String)level1.getSelectedItem();
       
      try{
          String qle ="select surname as 'Surname',middlename as 'Middle name',lastname as 'Last Name',regnumber as 'Reg. Number' from student where faculty ='"+fac+"' and department ='"+dept+"' and level = '"+lev+"'";
    pst = conn.prepareStatement(qle);
    rs = pst.executeQuery();
        jTable1.setModel(DbUtils.resultSetToTableModel(rs));
      }catch(Exception e){
          JOptionPane.showMessageDialog(null,e);
      }
       
       
   }
   
   public void filter_level(){
        String lev = (String)level1.getSelectedItem();
        switch(lev){
            case "100":
                general_gp();
                  fill_tables("100",1,t1100, l1100);
       fill_tables("100",2,t2100, l2100);
                level200.setVisible(false);
                level300.setVisible(false);
                level400.setVisible(false);
                level500.setVisible(false);
                jPanel6.setPreferredSize(new Dimension(1080,680));
                jPanel6.setMaximumSize(jPanel6.getPreferredSize());
                
                break;
                
            case "200":
                general_gp();
                  fill_tables("100",1,t1100, l1100);
       fill_tables("100",2,t2100, l2100);
       fill_tables("200",1,t1200, l1200);
       fill_tables("200",2,t2200, l2200);
               level300.setVisible(false);
                level400.setVisible(false);
                level500.setVisible(false);
                jPanel6.setPreferredSize(new Dimension(1080,910));
                jPanel6.setMaximumSize(jPanel6.getPreferredSize());
                break;
                
            case "300":
                general_gp();
                   fill_tables("100",1,t1100, l1100);
       fill_tables("100",2,t2100, l2100);
       fill_tables("200",1,t1200, l1200);
       fill_tables("200",2,t2200, l2200);
       fill_tables("300",1,t1300, l1300);
       fill_tables("300",2,t2300, l2300);
                 level400.setVisible(false);
                level500.setVisible(false);
                jPanel6.setPreferredSize(new Dimension(1080,1180));
                jPanel6.setMaximumSize(jPanel6.getPreferredSize());
                break;
                
            case "400":
                general_gp();
                 fill_tables("100",1,t1100, l1100);
       fill_tables("100",2,t2100, l2100);
       fill_tables("200",1,t1200, l1200);
       fill_tables("200",2,t2200, l2200);
       fill_tables("300",1,t1300, l1300);
       fill_tables("300",2,t2300, l2300);
       fill_tables("400",1,t1400, l1400);
       fill_tables("400",2,t2400, l2400);
                level500.setVisible(false);
                jPanel6.setPreferredSize(new Dimension(1080,1470));
                jPanel6.setMaximumSize(jPanel6.getPreferredSize());
                break;
                
            case "500":
                general_gp();
                 fill_tables("100",1,t1100, l1100);
       fill_tables("100",2,t2100, l2100);
       fill_tables("200",1,t1200, l1200);
       fill_tables("200",2,t2200, l2200);
       fill_tables("300",1,t1300, l1300);
       fill_tables("300",2,t2300, l2300);
       fill_tables("400",1,t1400, l1400);
       fill_tables("400",2,t2400, l2400);
       fill_tables("500",1,t1500, l1500);
       fill_tables("500",2,t2500, l2500);
        }
   }
   
   public void fill_tables(String level,int sem, JTable table, JLabel label){
       DecimalFormat df = new DecimalFormat("#.###");
       double total_credit = 0;double gp1;
       double total_grade = 0; 
       int getrow = jTable1.getSelectedRow();
      
       String regnum = jTable1.getModel().getValueAt(getrow, 3).toString();
       try{
           String qle ="select courseTittle as 'Course Tittle',courseCode as 'Course Code',creditLoad as 'Credit Load',score as 'Score'"
                   + ",grade as 'Grade',grade_unit as 'Grade Point' from course where regno = '"+regnum+"'  and level ='"+level+"' and semester"
                   + "='"+sem+"' ";
           pst = conn.prepareStatement(qle);
           rs = pst.executeQuery();
           table.setModel(DbUtils.resultSetToTableModel(rs));
           
           int row = table.getRowCount();
           for(int r = 0; r < row; r++){
               total_credit = total_credit + (int)table.getModel().getValueAt(r, 2);
               total_grade = total_grade + (int)table.getModel().getValueAt(r, 5);
           }
          
          
             gp1 = total_grade / total_credit ;
          label.setText("This Semester GP: "+ df.format(gp1));
           
       }catch(Exception e){
           JOptionPane.showMessageDialog(null,e);
       }
   }
   
   public void general_gp(){
       DecimalFormat df = new DecimalFormat("#.###");
       double total_credit = 0;double gp1;
       double total_grade = 0; 
       int getrow = jTable1.getSelectedRow();
        
       String regnum = jTable1.getModel().getValueAt(getrow, 3).toString();
       
       try{
           String sql = " select * from course where regno = '"+regnum+"'";
           pst = conn.prepareStatement(sql);
           rs = pst.executeQuery();
           
           while(rs.next()){
               total_credit = total_credit + rs.getInt("creditLoad");
                   total_grade = total_grade + rs.getInt("grade_unit");
                       }
           finalUnit.setText(df.format(total_credit));
           finalGrade.setText(df.format(total_grade));
           regn.setText(regnum);
           levelGP.setText(level1.getSelectedItem().toString());
           gp1 = total_grade / total_credit;
           
           gradeValue.setText(grade_level(gp1));
           
             String sql1 = " select * from student where regnumber = '"+regnum+"'";
           pst = conn.prepareStatement(sql1);
           rs = pst.executeQuery();
           if(rs.next()){
                         name.setText(rs.getString("surname") +"  "+rs.getString("middlename")+"  "+rs.getString("lastname"));

                       }
           
       }catch(Exception e){
           JOptionPane.showMessageDialog(null,e);
       }
   }
   public void printComponenet(Component component){
//       printBtn.setVisible(false);
  PrinterJob pj = PrinterJob.getPrinterJob();
  pj.setJobName(" Transcript ");

  pj.setPrintable (new Printable() {    
    public int print(Graphics pg, PageFormat pf, int pageNum){
      if (pageNum > 0){
      return Printable.NO_SUCH_PAGE;
      }

      Graphics2D g2 = (Graphics2D) pg;
      g2.translate(pf.getImageableX(), pf.getImageableY());
      component.paint(g2);
      return Printable.PAGE_EXISTS;
    }
  });
  if (pj.printDialog() == false)
  return;

  try {
        pj.print();
  } catch (PrinterException ex) {
        // handle exception
  }
}
}
